### ISSUE TITLE
Fully Connected Layer

### ISSUE THREAD

**Issue by yaduydk97** [alan4186/Hardware-CNN#8]
Is every input node multiplied with the same filter values or if each input node is multiplied with different sets of filter values?

**Comment by avisekh007** [comment]
Different sets of filter values.
The fully connected layer has 968 input activations, decomposing them into 10 outputs. So the weight matrix should be of 10x968. Check ffn_weight_rams.h file, it is the header to 10 other .mif files which contains 968 weights each. This can be implemented using 1024x24 Block Rams. Each weight size is of 3bytes (or 24 bits). 
It is a beautifully written code, but there are various issues in the code, so don't follow and simulate the code blindly. You can understand or use various modules inside this code on your own design.

**Comment by midn8hustlr** [comment]
> Is every input node multiplied with the same filter values or if each input node is multiplied with different sets of filter values?

Different sets of filter values.
The fully connected layer has 968 input activations, decomposing them into 10 outputs. So the weight matrix should be of 10x968. Check ffn_weight_rams.h file, it is the header to 10 other .mif files which contains 968 weights each. This can be implemented using 1024x24 Block Rams. Each weight size is of 3bytes (or 24 bits).
It is a beautifully written code, but there are various issues in the code, so don't follow and simulate the code blindly. You can understand or use various modules inside this code on your own design.

**Comment by yaduydk97** [comment]
Thank you for your response
